edition = "2024"

newline_style = "Unix"
indent_style = "Block"

blank_lines_upper_bound = 2

array_width = 80
chain_width = 80
max_width = 100

imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

match_arm_blocks = false
match_block_trailing_comma = true

use_field_init_shorthand = true
reorder_impl_items = true
where_single_line = false
